{'author': 'Nedas Zilinskas',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['security/res_groups.xml',
          'data/product_pricelist.xml',
          'views/res_partner_hcategory.xml',
          'views/res_partner.xml',
          'views/assets.xml'],
 'demo': [],
 'depends': ['product', 'sale', 'website_sale', 'partner_category_hierarchy'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/website_sale_pricelist_visibility/12.0',
 'name': 'Pricelist by Partner Category',
 'price': 10.0,
 'qweb': [],
 'summary': 'Manage Pricelists by Partner Category',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '12.0.1.0.0',
 'website': 'https://demo.minilini.com'}

