{'author': 'Nedas Zilinskas',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['security/res_groups.xml',
          'security/ir.model.access.csv',
          'views/res_partner.xml',
          'views/res_partner_hcategory.xml',
          'views/assets.xml'],
 'demo': [],
 'depends': ['base', 'web'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/partner_category_hierarchy/12.0',
 'name': 'Partners Hierarchy',
 'price': 10.0,
 'qweb': [],
 'summary': 'Build parters hierarchy by specifying partner categories',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '12.0.1.0.0',
 'website': 'https://demo.minilini.com'}

